title: Auditr
description: Detecting confidentiality and availability vulnerabilities in Java application
google_analytics: 
show_downloads: true
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions
